[package]
name = "mf-utils"
version = "0.0.1"
edition = "2021"
description = "markflow utils"
license = "MIT"

[dependencies]
regex = "1.10.4"
fs_extra = "1.2.0"
serde = { version = "1.0", features = ["derive"] }
